In [1]:
import numpy as np
import pandas as pd
import scanpy as sc

import json_numpy
import sys
sys.path.append('..')
from tools.utils.gzip_str import *

In [2]:
adata = sc.read_h5ad('../../../oscb/user_storage/Benchmarks/TSepithelial_1755926617806/QC/TS_epithelial_scanpy.h5ad')
adata

AnnData object with n_obs × n_vars = 104148 × 2000
    obs: 'organ_tissue', 'method', 'donor', 'anatomical_information', 'n_counts', 'n_genes', 'cell_ontology_class', 'free_annotation', 'manually_annotated', 'compartment', 'gender', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_20_genes', 'total_counts_mt', 'log1p_total_counts_mt', 'pct_counts_mt', 'total_counts_ribo', 'log1p_total_counts_ribo', 'pct_counts_ribo', 'total_counts_hb', 'log1p_total_counts_hb', 'pct_counts_hb', 'outlier', 'doublet_score', 'predicted_doublet', 'clf_doublet', 'clf_score', 'leiden', 'louvain'
    var: 'gene_symbol', 'feature_type', 'ensemblid', 'highly_variable', 'means', 'dispersions', 'dispersions_norm', 'mean', 'std', 'n_cells', 'mt', 'ribo', 'hb', 'n_cells_by_counts', 'mean_counts', 'log1p_mean_counts', 'pct_dropout_by_counts', 'total_counts', 'log1p_total_counts'
    uns: '_scvi', '_training_mode', 'dendrogram_cell_type_tissue', 'dendrogram_computational_compartment_assignment', 'dendrogram_consensus_prediction', 'dendrogram_tissue_cell_type', 'donor_colors', 'donor_method_colors', 'hvg', 'leiden', 'log1p', 'louvain', 'method_colors', 'neighbors', 'organ_tissue_colors', 'pca', 'scrublet', 'sex_colors', 'tissue_colors', 'umap'
    obsm: 'X_pca', 'X_scvi', 'X_scvi_umap', 'X_tsne', 'X_tsne_3D', 'X_umap', 'X_umap_3D'
    varm: 'PCs'
    layers: 'decontXcounts', 'logCP10K', 'normalized_X', 'raw_counts'
    obsp: 'connectivities', 'distances'

In [3]:
adata.obs

,organ_tissue,method,donor,anatomical_information,n_counts,n_genes,cell_ontology_class,free_annotation,manually_annotated,compartment,...,total_counts_hb,log1p_total_counts_hb,pct_counts_hb,outlier,doublet_score,predicted_doublet,clf_doublet,clf_score,leiden,louvain
AACAGGGCATGTGCTA_TSP6_Liver_NA_10X_1_1,Liver,10X,TSP6,nan,14151.0,3809,hepatocyte,Hepatocyte,True,epithelial,...,0.0,0.000000,0.000000,False,0.051365,False,1.0,1.870304e+02,20,30
AATGAAGTCTAAGGAA_TSP6_Liver_NA_10X_1_1,Liver,10X,TSP6,nan,10303.0,3194,hepatocyte,Hepatocyte,True,epithelial,...,2.0,1.098612,0.017524,False,0.012593,False,0.0,2.711604e-18,20,31
ACAGAAAAGCTGTCCG_TSP6_Liver_NA_10X_1_1,Liver,10X,TSP6,nan,9391.0,3089,hepatocyte,Hepatocyte,True,epithelial,...,0.0,0.000000,0.000000,False,0.006802,False,0.0,2.711604e-18,20,31
ACGATGTTCGACTCCT_TSP6_Liver_NA_10X_1_1,Liver,10X,TSP6,nan,4634.0,1755,hepatocyte,Hepatocyte,True,epithelial,...,1.0,0.693147,0.020137,False,0.008769,False,0.0,2.711604e-18,20,31
ACGTTCCAGAACCCGA_TSP6_Liver_NA_10X_1_1,Liver,10X,TSP6,nan,33370.0,7411,intrahepatic cholangiocyte,BECS,True,epithelial,...,4.0,1.609438,0.008048,False,0.253687,False,1.0,3.427481e+01,13,14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
TGACAGTAGATGGCGT_TSP2_Vasculature_Aorta_10X_1_2,Vasculature,10X,TSP2,Aorta,10354.0,2474,epithelial cell,epithelial cell,True,epithelial,...,1.0,0.693147,0.009441,False,0.077764,False,1.0,1.118596e+01,29,35
TGTTGGATCGACATCA_TSP2_Vasculature_Aorta_10X_1_2,Vasculature,10X,TSP2,Aorta,15677.0,3244,epithelial cell,epithelial cell,True,epithelial,...,0.0,0.000000,0.000000,False,0.108149,False,1.0,1.118596e+01,29,35
TTGGATGGTGGCTACC_TSP2_Vasculature_Aorta_10X_1_2,Vasculature,10X,TSP2,Aorta,18638.0,3382,epithelial cell,epithelial cell,True,epithelial,...,2.0,1.098612,0.010706,False,0.096774,False,1.0,1.118596e+01,29,35
CTTGATTTCTTGCAAG_TSP2_Vasculature_Aorta_10X_2_2,Vasculature,10X,TSP2,Aorta,36555.0,5109,epithelial cell,epithelial cell,True,epithelial,...,1.0,0.693147,0.002735,False,0.113444,False,1.0,1.118596e+01,29,35
TCGACGGCATGGAATA_TSP2_Vasculature_Aorta_10X_2_2,Vasculature,10X,TSP2,Aorta,6943.0,1801,epithelial cell,epithelial cell,True,epithelial,...,0.0,0.000000,0.000000,False,0.083993,False,1.0,7.637899e+00,29,35

In [4]:
adata.obs.drop(['n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_20_genes', 'total_counts_mt', 'log1p_total_counts_mt', 'pct_counts_mt', 'total_counts_ribo', 'log1p_total_counts_ribo', 'pct_counts_ribo', 'total_counts_hb', 'log1p_total_counts_hb', 'pct_counts_hb', 'outlier', 'doublet_score', 'predicted_doublet', 'clf_doublet', 'clf_score'], axis=1, inplace=True)
adata.obs

,organ_tissue,method,donor,anatomical_information,n_counts,n_genes,cell_ontology_class,free_annotation,manually_annotated,compartment,gender,leiden,louvain
AACAGGGCATGTGCTA_TSP6_Liver_NA_10X_1_1,Liver,10X,TSP6,nan,14151.0,3809,hepatocyte,Hepatocyte,True,epithelial,male,20,30
AATGAAGTCTAAGGAA_TSP6_Liver_NA_10X_1_1,Liver,10X,TSP6,nan,10303.0,3194,hepatocyte,Hepatocyte,True,epithelial,male,20,31
ACAGAAAAGCTGTCCG_TSP6_Liver_NA_10X_1_1,Liver,10X,TSP6,nan,9391.0,3089,hepatocyte,Hepatocyte,True,epithelial,male,20,31
ACGATGTTCGACTCCT_TSP6_Liver_NA_10X_1_1,Liver,10X,TSP6,nan,4634.0,1755,hepatocyte,Hepatocyte,True,epithelial,male,20,31
ACGTTCCAGAACCCGA_TSP6_Liver_NA_10X_1_1,Liver,10X,TSP6,nan,33370.0,7411,intrahepatic cholangiocyte,BECS,True,epithelial,male,13,14
...,...,...,...,...,...,...,...,...,...,...,...,...,...
TGACAGTAGATGGCGT_TSP2_Vasculature_Aorta_10X_1_2,Vasculature,10X,TSP2,Aorta,10354.0,2474,epithelial cell,epithelial cell,True,epithelial,female,29,35
TGTTGGATCGACATCA_TSP2_Vasculature_Aorta_10X_1_2,Vasculature,10X,TSP2,Aorta,15677.0,3244,epithelial cell,epithelial cell,True,epithelial,female,29,35
TTGGATGGTGGCTACC_TSP2_Vasculature_Aorta_10X_1_2,Vasculature,10X,TSP2,Aorta,18638.0,3382,epithelial cell,epithelial cell,True,epithelial,female,29,35
CTTGATTTCTTGCAAG_TSP2_Vasculature_Aorta_10X_2_2,Vasculature,10X,TSP2,Aorta,36555.0,5109,epithelial cell,epithelial cell,True,epithelial,female,29,35
TCGACGGCATGGAATA_TSP2_Vasculature_Aorta_10X_2_2,Vasculature,10X,TSP2,Aorta,6943.0,1801,epithelial cell,epithelial cell,True,epithelial,female,29,35

In [5]:
del adata.obsm["X_tsne"]
del adata.obsm["X_tsne_3D"]
adata

AnnData object with n_obs × n_vars = 104148 × 2000
    obs: 'organ_tissue', 'method', 'donor', 'anatomical_information', 'n_counts', 'n_genes', 'cell_ontology_class', 'free_annotation', 'manually_annotated', 'compartment', 'gender', 'leiden', 'louvain'
    var: 'gene_symbol', 'feature_type', 'ensemblid', 'highly_variable', 'means', 'dispersions', 'dispersions_norm', 'mean', 'std', 'n_cells', 'mt', 'ribo', 'hb', 'n_cells_by_counts', 'mean_counts', 'log1p_mean_counts', 'pct_dropout_by_counts', 'total_counts', 'log1p_total_counts'
    uns: '_scvi', '_training_mode', 'dendrogram_cell_type_tissue', 'dendrogram_computational_compartment_assignment', 'dendrogram_consensus_prediction', 'dendrogram_tissue_cell_type', 'donor_colors', 'donor_method_colors', 'hvg', 'leiden', 'log1p', 'louvain', 'method_colors', 'neighbors', 'organ_tissue_colors', 'pca', 'scrublet', 'sex_colors', 'tissue_colors', 'umap'
    obsm: 'X_pca', 'X_scvi', 'X_scvi_umap', 'X_umap', 'X_umap_3D'
    varm: 'PCs'
    layers: 'decontXcounts', 'logCP10K', 'normalized_X', 'raw_counts'
    obsp: 'connectivities', 'distances'

In [6]:
adata.write_h5ad('../../../oscb/user_storage/Benchmarks/TSepithelial_1755926617806/QC/TS_epithelial_scanpy_s.h5ad', compression='gzip')

In [29]:
def regularise_df(df, drop_single_values=False):
    df = df.dropna(axis=1, how='all')
    res = df
    if drop_single_values == True:
        for col in df.columns:
            if len(df[col].unique()) == 1:
                res = res.drop(col,axis=1)
    return res

# Convert dataframe to dict for cell type selection
def df_to_dict(df):
    df_dict = {}
    # df = regularise_df(df)
    df = drop_num_col(df)
    for col in df.columns:
        col_dict = {}
        if len(df[col].unique()) < 500 and isinstance(df[col][0], str): # The known human cell types are less than 500
            col_dict[col] = [x for x in df[col].unique().tolist() if isinstance(x, str) or not math.isnan(x)]
            # col_dict[col] = df[col].unique().tolist()
            df_dict[col] = col_dict
    
    return df_dict

# Drop numerical columns for cell type annotation
def drop_num_col(df):
    col_to_drop = []

    for i, v in df.dtypes.items():
        if 'float' in str(v) or 'int' in str(v) or is_number(df[i][0]):
            col_to_drop.append(i)
    
    if len(col_to_drop) > 0:
        df = df.drop(columns=col_to_drop)
    
    return df


def rename_col(df, pattern):
    import re
    for name in df.columns.values:
        if re.match(pattern, name):
            df.rename(columns={name: pattern}, inplace=True)
            break
    return df

def is_number(s):
    try:
        float(s)
        return True
    except ValueError:
        pass
 
    try:
        import unicodedata
        unicodedata.numeric(s)
        return True
    except (TypeError, ValueError):
        pass
 
    return False

In [30]:
obs = regularise_df(adata.obs)
obs_dict = obs.to_dict('list')
cell_metadata = gzip_dict(obs_dict)

In [31]:
sys.getsizeof(cell_metadata)/1024/1024

0.6648263931274414

In [32]:
cell_metadata

'H4sIAGhKqWgC/+zdXW9cx5mu4b9i6Hj2YH1/5MzjOLMD2IEBeYINBIHQJnskImS30mx6W9h/flez3rctzSQZO5ZkkbyO7vt5JJHs7rWqatVatP/fs/3h5Wb34nh1e3u3ffabz/707Kur77eHZ//yGSHvR749bC5ebTeUUkoppZRSSimllFJKKaWUUkoppZRSSimllFJKKaWU0iejX725ef3qxR/2l9tfkp5vrq++3xzevPj3683uUqPRaDQajUaj0Wg0Go1Go9FoNBqNRqPRaDQajUaj0Wg0Go1Go9FoNBqNRqPRaDQajUaj0Wg0Go1Go9FoNBrNQ2q+3e9e3m0ZY4w9dvt6c3NTJgBKKaWUUkoppZRSSimllFJKKaWUUkoppZRSSimllFJKKaWUUkoppZRSSimllFJKKaWUUkoppZRSSp+o/sdxe7i7ZYwxxhhjjDHGGGOMMcYYY4wxxhhjjDHGGGOMMcYYY4wxxhhjjDHGGGOMMcYYY4wxxhhjjDHGGGOMMcYYY4wxxhhjjDHGGGOMMcYYY4wxxhhjjDHGGGPvw758swUAgJ+E322OAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA8LPw/C9XO0RERERERERERERERERERERERERERERERMSHxv+93RyOhBBCCCGEEEIIIYQQQgghhBBCCCGEEEIIIYQQQgghhBBCCCGEEEIIIYQQQgghhBBCCCGEEEIIIYQQQgghhBBCCCGEEEIIIYQQQgghhBBCCCGEEEIIIYQQQgghhBBCCCGEEEIIIYQQQgghhBBCCCGEEEIIIYQQQgghhBBCCCGEEEIIIYQQQgghhBBCCCGEEEIIIYQQQgghhBBCCCGEEEIIIYQQQgghv758s9ldHLabW84555xzzjnnnHPOP0k/7G+Pm+OWc84555xzzjnnnHPOOX/M/rvN8QPj+V+udu+TH/4nhk/7CEDEf55+kYGQ9yVfvtkCwD/C15ubm83hzUfS/zhuD3e3jDHGPv4ITCl9VGoQ/ezZt/vdy7vtx7Kv724vrhljjDHGGGOMMcYYY4wxxhhjjDHGGGOMMcYYY4wxxhj7IPYLf2P8q6vvt4f734c5bC5ebTeUUvpU9Twe/nd5vrm++n5zePPi3683u0uNRqPRaDQajUaj0Wg0msfZfNz/MhP7tMz/zeNX9rf+D9v/YKPyH8mbm9evXvxhf7mVpI+VzKEajUaj0Wg0Go1Go9FoNBqNRqPRaDQajUaj0Wg0Go1Go9FoNBqNRqPRaDQajUaj0Wg0Go1Go9FoNBqNRqPRaDQajUaj0Wg0Go1Go9FoNBqNRqPRaDQajUaj0Tz4/4fdqzc3d7eMMcYYY4wxxhhjjDHGGGOMMcYYY4wxxhhjjDHGGGOMMcYYY4wxxhhjjDHGGGOMMcYYY4wxxhhjjDHGGGOMMcYYY4wxxhhjjDHG2N+yL99sAQAAAAAAAAAAAAAAfiH+7Xpzebk9UEoppZRSSimllFJKKaWUUkoppZRSSimllH5s/WpzeLl98fvdcXt7vNptVSqVSqVSqVQqlUqlUqlUKpVKpVKpVCqVSqVSqVQqlUqlUqlUKpVKpVKpVCqVSqVSqVQqlUqlenjV3e4l/nr85rC/PW6O24fqz28219fvHlIqlUqlUn286i9XO0RERERERERERERERERERERERERERERERETEp8hvX725ubtljDHGGGOMMcYYY4wxxhhjjDHGGGOMMcYYY4wxxhhjjDHGGGOMMcbYA7L97uXdljHGGGPs4djvNkcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD4EPjqbvfyHb65ef3qxR/2l1tJkt5P+vru9uKaMcYYY4wxxhhjjDHGGGOMMcYYY4wxxhhjjDHGGGOMMcYYY4wxxhhjjDHGGGOMMcYYY4wxxhhjjDHGGGOMMcYYY4wxxhhjjDHGGGOMMcYYY4wxxhhjjDHGGGOMMcYYY4wxxhhjjDHGGGOMMcYYY4wxxhhjjDHGGGOMMcYYY4wxxhhjjDHGGGOMMcYYY4wxxhhjjDHGGGOMMcYYY4wxxhhjjDHGGGOMMcYYY4x9QPvj5vbi7npzvDuIoiiKoiiKoiiKoiiKoiiKoiiKoiiKoiiKoiiKoiiKoiiKoiiKoiiKoiiKoiiKoiiKoiiKoiiKoiiKoiiKoiiKoiiKoiiKoiiKoiiKoiiKoiiKoiiKoiiKoiiKoiiKoiiKoiiKoiiKoiiKoiiKoiiKoiiKoiiKoiiKoiiKoiiKoiiKoiiKoiiKoiiKoiiKoiiKoiiKoiiKoiiKoiiKoiiKoiiKoiiKoiiKoiiKoiiKoiiKoiiKoiiKoiiKoiiKoiiKoiiKoiiKoiiKoiiKoiiKoiiKoiiKoiiKoiiKoiiKoiiKoiiKoiiKoiiKoiiKHyz+2/Xm8nJ7oJRSSimllFJKKaWUUkoppZRSSimllFJKKaWUUkoppZRSSimllFJKKaWUUkoppZRSSimllFJKKaWUUkoppZRSSimllFJKKaWUUkoppZRSSimllFJKKaWUUkoppZRSSimllFJKKaWUUkoppZRSSimllFJKKaWUUkoppZRSSimllFJKKaWUUkoppZRSSimllFJKKaWUUkoppZRSSimllFJKKaWUUkoppZRSSimllFJKKaWUUkoppZRSSimllFJKKaWUUkoppZRSSimllFJKKaWUUkofpn61Obzcvvj97ri9PV7ttiqVSqVSqT5Cdbd7iYiIiIiIiIiIiIiIiIiIiIifPr++u7243jLGGGOMMcYYY4wxxhhjjDHGGGOMMcYYY4wxxhhjjDHGGGOMMcYYY4wxxhhjjDHGGGOMMcYYY4wxxhhjjDHGGGOMMcYYY4wxxhhjjDHGGGOMMcYYY4wxxhhjjDHGGGOMMcYYY4wxxhhjjDHGGGOMMcYYY4wxxhhjjDHGGGOMMcYYY4wxxhhjjDHGGGOMMcYYY4wxxhhjjDHGGGOMMcYYY4wxxhhjjDHGGGOMMcYYY4wxxhhjjDHGGGOMMcYYY4wxxhhjjDHGGGOMMcYYY4wxxhhjjDHGGGOMMcYYY4wxxhhjjDHGGGOMMcYYY4wxxhhjjDHGGGOMMcYYY4wxxhhjjDHGGGOMMcYYY4wxxhhjjDHGGGOMMcYYY4wxxhhjjDHGGGOMMcYYY4wxxhhjjDHGGGOMMcYYY4wxxhhjjDHGGHuM9s1md3HYbm754/HnN5vr6xe/3x23t8er3Vb1eKpvX725ubtljDHGGGOMMcYYY4wxxhhjjDHGGGOMMcYYY4wxxhhjjDHGGPuZdthcvNpuKKWUUkop/VT1j5vbi7vrzfHusBVFURRFURRFURRFURRFURRFURRFURRFURRFURRFURRFURRFURRFURRFURRFURRFURRFURRFURRFURRFURRFURRFURRFURRFURRFURRFURRFURRFURRFURRFURRFURRFURRFURRFURRFURRFURRFURRFURRFURRFURRFURRFURRFURRFURRFURRFURRFURRFURRFURRFURRFURRFURRFURRFURRFURRFURRFURRFURRFURRFURRFURRFURRFURRFURRFURRFURRFURRF8bHFP5d8sz2+2l8++81nf3rWNv/n9DcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA4FPG7c3mcLzd/rUTBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQhCcU/K/OAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOAh4vZmczjebv/aCYIgCIIgCILwYIJLGQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/3U6QRAEQfDfWgV4cItLbzUAgAlBEARBEAQXWAAAAAAAYItPEARBEARBEARBcL8JAAAAAAAAAAAAAAAAAAAAAAAAAAAAwG/aCoIgCIIgCIIgCIIgCIIgCIIgCIIgCILgv74GAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA8OBxe7M5HG+3f+0EQRAEQRAEQRAEQRAEQRAEQRAEQRAeXHBj9xG/aU/xkwYAAAAAAAAAAAAAAAAAAAC/Vy8IgiAIgiAIguCZfQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAeMK4vdkcjrfbv3aCIAiCIAiCIAjCew5/Lulyv9sfnv3msz89+/b5N9PpzxERERERERERERERERERERERERHxUXFGRERERERERERERERERERERER84BwQERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERHxyXNExPfG3vuAnzDbhhBCCCGEEEIIIYQQQgghhBBCCCGEEEIIIYQQQgghhBBCCCGEEEIIIYQQQgghhBBCCCGEEEIIIYQQQgghhBBCCCGEEEIIIYQQQgghhBBCCCGEEEIIIYQQQgghhBBCCCGEEEIIIYQQQgghhBBCCCGEEEIIIYQQQgghhBBCCCGEEEIIIYQQQgghhBBCCCGEEEIIIYQQQgghhBBCCCGEEEIIIYQQQgghhBBCCCGEEEIIIYQQQgghhDxt6QghhBBCCCGEEEIIIYQQQgghhBBCCCGEEEIIIYQQQgghhBBCCCGEEEIIIYQQQgghhBBCCCGEEEIIIYQQQgghhBBCCCGEEEIIIYQQQgghhBBCCCGEEEIIIYQQQgghhBBCCCGEEEIIIYQQQgghhBBCCCGEEEIIIYQQQgghhBBCCCGEEEIIIYQQQgghhBBCCCGEEEIIIYQQQgghhBBCCCGEEEIIIYQQQj4JWRERERERET8SF0RERERERET8xWwbQggh5AmLh30IeU/SI+InxwEREREREREREREREREREREREREREREREfGRcnxPnBDxwXNGRERExL/Jp/5fV8v/ink7EEIIIYQQQgghhBBCCCGEEEIIIYQQQgghhBBCCCGEEEIIIYQQQgghhBBCCCGEEEIIIYQQQgghhBBCCCGEEEIIIYQQQgghhBBCCCGEEEIIIYQQQgghhBBCCCGEEEIIIYQQQggh5OnJSAghhBBCCCGEEEIIIYQQQgghhJCfKR45IIQQQgghhBBCCCGEEEIIIYQQQgghhBBCCCGEEEIIIYQQQgghhBBCCCGEEEIIIYQQQgghhBBCCCGEEEIIIYQQQgghhBBCCCGEEEIIIYQQQgghhBBCCCGEEEIIIYQQQgghhBBCCCGEEEIIIYQQQgghhBBCCCGEEEIIIYQQQgghhBBCCCGEEEIIIYQQQgghhBBCCCGEEEIIIYQQQgghhBBCCCGEEEIIIYQQQgghhBBCCCGEEEIIIYQQQgghhBBCCCGEEEIIIYQQQgghhBBCCCGEEEIIIYQQQgghhBBCCCGEEEIIIYQQQgghhBBCCCGEEEIIIYQQQgghhBBCCCGEEEIIIYQQQgghhBBCCCGEEEIIIYQQQgghhBBCCCGEEEIIIYQQQgghhBBCCCGEEEIIIYQQQgghhBBCCCGEEEIIIYQQQgghhBBCCCGEEEIIIYQQQgghhBBCCCGEEEIIIYQQQgghhBBCCCGEEEIIIYQQQgghhBBCCCGEEEIIIYQQQgghhBBCCCGEEEIIIYQQQgghhBBCCCGEEEIIIYQQQgghhBBCCCGEEEIIIYQQQgghhBBCCCGEEEIIIYQQQgghhBBCCCGEEEIIIYSQxySIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIgPiB0iIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIj4Z+v81ICIiIiL6/3shIiIiIiIiIiIiouc8EBERERERERERERERERERERERERERERERERERERERERERERH99+IRERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERE/Dbb4T9Hxg4iIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIH5d/LrLZbY77m6uLzfWLq91/7g83m+PVfvfsN5/96dluszv9VQAAAAAAAAAAAAAAAAAAAACAR4fnd68Pm8urzetXm5enR2YuPlT5zeawP15dUkoppZRSSimllFJKKaWUUkoppZRSSimllFJKH5vub4/bw9X+IAiCIAjCJx/8PhUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAU8GXu8v9zfZ4uLq7EUVRFEVRFEVRFEVRFEVRFEVRFEVRFEVRFEVRFEVRFEVRFEVRFEVRFEVRFEVRFEVRFEVRFEVRFEVRFEVRFEVRFEVRFEVRFEVRFEVRFEVRFEVRFEVRFEVRFEVRFEVRFEVRFEVRFEVRFEVRFEVRFEXx4cWv30iSJEmSJEmSJEmSJEmSJEmSJEmSJEmSJEmSJEmSJEmSJEmSJEmSJEnS+067zQ4AAH4Svv78WwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA+GV4/gUiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIuKvy91mBwAAAAAAAAAAAAAAAAAAAAAAAAAAAPDh8PnxcLUhhBBCCCGEEEIIIYQQQgghhBBCCCGEEEIIIYQQQgghhBBCCCGEEEIIIYQQQgghhBBCCCGEEEIIIYQQQgghhBBCCCGEEEIIIYQQQgghhBBCCCGEEEIIIYQQQgghhBBCCCGEEEIIIYQQQgghhBBCCCGEEEIIIYQQQsgTkj9ud0UvrreCIAiCIAiCIAiCIAiCIAiCIAiCIAiCIAiCIAiCIAiCIAiCIAiCIAiCIAiCIAiCIAiCIAiCIAiCIAiCIAiCIAiCIAiCIAiCIAiCIAiCIAiPMWx/2F8crnacc84555xzzjnnnH+SvtvsAAAAAAAA4APh68+//VB4/kXl5rvL/c1295P04tX29vizJb8TPg3+nCOKUvoh9J8bq5+ObI6Hqw0h5GfL928/1/pO2O2/2B922/u/db25OFzdbK5fXm92lwqFQqFQKD5I8fbc+47bRwMAAPhVcXm1ef3qsHl5IwiCIAiCIAiCIAiCIAiCIAiCIAiCIAiCUMJhe3G8u73/lZ+r3d2tSqVSqVQqlUqlUqlUKpVKpVKpVCqVSqVSqVQqlUqlUqlUKpVKpVKpVCrV46j+76t9/T8VvC/xH7UEeG/4ZnPYH68uKaWUUkopfY+62R23h6v94Z/x1/vbnx1+yff7GD/fJxY+5tv18d/Sx34Jt/1hf3G42tkdcc1MKaWUUkoppZRSSimllFJKKaWUUkop/cj6/O6766vdy7vNtSRJkiRJkiRJkiRJkiRJkiRJkiRJkiRJkiQ9ruS/NgQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADwpf7A+77eZ/bY8XkiRJkiRJkiRJkiRJTyP9YXt32B+2x6udSqVSqVQqlUqlUqlUKpVKpVKpVKpfUj2/uN4eJEmSJEmSJEmSJOkjJr8SCAAAAAAAAAAAAAAA8ODx26vb4+aaMcYYY4wxxhhjjDH2qdo3h/0PVzecc84555xzzjnn/93tUvCf5p5KY+ypj26ff3e5v9nuKKWUUkoppZRSSimllFJKKaWU/j394tX29kgIIYQQQgghhBBCCCGEEEIIIYQQQgh52OJ/SAYAAAAAAAAAAAAAAAAAAAAAAAAAAACfJD7fHbeHq/2Bc8750/Vv9reCIAiPJXz9+bcAAACPC8+/QERERERERERERERERERERERERERERERERERERERERERERERERESs9J/Xf6j/U4DvLvc3W0oppZRSSimllFJKKaWUUkoppZRSSimllFJKKaWUUkoppZRSSimllFJKKaWUUkoppZRSSimllFJKKaWUUkoppZRSSimllFJKKaWUUkoppZRSSimllFJKKaWUUkoppZRSSimllFJKKaWUUkoppZRSSimllFJKKaWUUkoppZRSSimllFJKKaWUUkoppZRSSin9lfS3V5vXrw6blzeCIAiCIAiCIAiCIAiCIAiCIAiCIAiCIAiCIAiCIAiCIAiCIAiCIAiCIAiCIAiCIAiCIAiCIAiCIAiCIAiCIAjCBwif7w/HzR+3u+0Xm+83CoVCoVAoFAqFQqFQKBQKhUKhUCgUCoVCoVAoFAqFQqFQKBQKhUKhUCgUCoVCoVAoFAqFQqFQKBQKhUKhUCgUCoVCoVAoFAqFQqFQKBQKhUKhUCgUCoVCoVAoFAqFQqFQKBQKheITKb7YH/a7zeHN54fj9nC1vdXpdDqdTqfT6XQ6nU6n0+l0Op1Op9PpdDqdTqfT6XQ6nU6n0+l0Op1Op9PpdDqdTqfT6XQ6nU6n0+l0Op1Op9PpdDqdTqfT6XQ6nU6n0+l0Op1Op9PpdDqdTqfT6XQ6nU6n0+l0Op1Op9PpdDqdTqfT6XQ6nU6n0+l0Op1Op9PpdDqdTqfT6XQ6nU6n0+l0Op1Op9PpdDqdTqfT6XQ6nU6n0+l0Op1Op9PpdDqdTqfT6XQ6nU6n0+l0Op1Op9PpdDqdTqfT6XQ6nU6n0+l0Op1Op9PpdDqdTqfT6XQ6nU6n0+l0Op1Op9PpdDqdTqfT6XQ6nU6n0+l0Op1O99O63WYHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJdXt8fNNWMPxV4f9j9c3fC/5z97CPhF/xgAAD4uvt5eXm2uf3s/K36m+AnFN29Nc5z/Wu68VCiM/Q/ZT5eMN/dv8rvX5TqdTqfT6XQ6nU6n0+l0Op1Op9PpdDqdTqfT6XQ63cfq3n2e9g/bu8OeMcYYY4yxB2bvb0UMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAkP9v+s3rV4fNyxtBEARBEARBEARBEARBEARBEARBEARBEARBEARBEARBEARBEARBEARBEARBEARBEARBEARBEARBEARBEARBEARBEARBEARBEARBEARBEARBEARBEISfFw7bi+Pd7ea7y/3N1e7uVqVSqVQqlUqlUqlUKpVKpVKpVCqVSqVSqVQqlUqlUqlUKpVKpVKpVCqVSqVSqVQqlUqlUqlUKpVKpVKpVCqVSqVSqVQqlUqlUqlUKpVKpVKpVCqVSqVSqVQqlUqlUqlUKpVKpVKpVCqVSqVSqVQqlUqlUqlUKpVKpVKpVCqVSqVSqVQqlUqlUqlUKpVKpVKpVCqVSqVSqVQqlUqlUqlUKpVKpVKpVCqVSqVSqVQqlUqlUqlUKpVKpVKpVCqVSqVSqVQqlUqlUqlUKpVKpVKpVCqVSqVSqVQqlUqlUqlUKpVKpVKpVCqVSqVSqVQqlUqlUqlUKpVKpVKpVCqVSqVSqVQqlUqlUqlUKpVKpVKpVCqVSqVSqVQqlUqlUqlUKpVKpVKpVCqVSqVSqVQqlUqlUqlUKpVKpVKpVCqVSqVSqVQqlUqlUqlUKpVKpVKpVCqVSqVSqVQqlUqlUqlUKpVKpVKpVCqVSqVSqVQqlUqlUqlUKpVKpVKpVCqVSqVSqVQqlUqlUqlUKpVKpVKpVCqVSqVSqVQqlUqlUqlUKpVKpVKpVCqVSqVSqVQqlUqlUqlUKpVKpVKpVCqVSqVSqVQqlUqlUqlUKpVKpVKpVCqVSqVSqVQqlUqlUqlUKpVKpVKpVCqVSqVSqVQqlUqlUqlUKpVKpVKpVCqVSqVSqVQqlUqlUqlUKpVKpfo51W6zAwAAAAB4Wri82rx+ddi8vBEE4e8EF80qlUqlUj3o6svd5f7icLXb3ocf+K/q73wYvzS8Pux/uLrZXPO/7S53AQAAAAAAAAAAAAAAAAAAAAAAAAAAAOB/wuf7w3FDCCGEEEIIIYQQQgghhBBCCCGEEEIIIYQQQgghhBBCCCGEEEIIIYQQQgghhBBCCCGEEEIIIYQQQgghhBBCCCGEEEIIIYQQQgghhBBCCCGEEEIIIYQQQgghhBBCCCGEEEIes+w2OwAAAPifsMmZs8qfT3/y4mJ/tzvePvvNZ39qm6Hr/7X5l8/atgsZpnU8ybLO833Rtc16krWPYm265SRdU/5y/TdDd/9v5mFp74tmauqf9HNz36xj29z/m35ap/pXu/uvNrbL/fftuiW+Rl9/kLHrhvr9h+H+b67T2t1zaO7zNE5z/ZLjGF9yvP8K3TKt9acYxqV+yfX+S05919VXsCz3f3Oap/ufbp7nteY2f/6+vtZxaZr6/iz1hSzjcP9Ph3lu76Wd2uX+7/bLfP83pngh09DWH2Nq+ipL+bL1zZjuf+Blbup73i1DHz/YutQ/qWy7sb6j/VS/2NCtbX3RQ1u/xlh/wKn8SX3Hu6H+03Yd64sa62tZmr6vX7uPFzkO9TMpn/j5RcYXmetrWMalfo5jG29I+Tzvm7Wrn1950fXVN1P9uIauuf/+4zzXLzpNy1Dfn3oIjO261g+4z5d2/w/6sY2jaRrvP6apqZ/G2MYBMLT1Xer7egAu7TzWr7zUl9wP9YOeu6Z+BGu8wVNTZSiH6v03X6Ym3qWlrwdzmy8ofv6hqV+jvM95HMZ7UX6cKY6WOGXm+id9Ny3xHiz105rroTos9Qde+/gU1/o91rYeqXMcOsMUx/zYx1vQno+hePPW+pXm/BC7PHT7eEHlU65fe53r29oPcZwu9cwrp0ecBk0/xEtr61E2NPUgGtcxDv+5r695zuGhfGj17VnqMdOtdbjo+7V+rO3YLF2+6ff/eGz6+rN3SxwRXX1141LfpvJ+DW38kzrGdOXMqC9nHeq5UkaWNQ7r+srLTxZHR1dPzG6Kz7rr6pnRzXVkacb6SY5dnmVrPf3LANHevwHjOMfnFUPKONbjqJ/zkKwvoR2nOLnHsb5jXR8Hc/0XZSSMz2Wc63u7tl18MF18jfJncSCNcYZOUz2Hl/qGlW8fQ+0w1feyix+wj3euG2OgKudnU0+/etZ3yxKH7VAPrXGo70Y5fOf4p109Y8epnizlYBvqwTbWv1qG6jil68czx4/XrlMc8HNTX0E5FuoXb5Y5htw1Bps2x834bsMYg+DU17N5GaY8gmNoKYNy/UTXJWaero5Y/drF4TjVY3ocY5ya46/2ff3w+6YenUuXp8e4xlw111FoaWOs65v6J2WGqgfw0OfpHUd4E692meunsbb1+F3mJWaopa+HTz/GwLSOQ0yVTbwv9ecqR3qdLfp4j9tpburHscbZUgbj+uGX2bWrg0Kf72kdgdaYC9p5yHl3ieOkjKlTjPUxK9QDeVrqAd72yzrEF6sfTDk8YyCME61r42WffrT6V9v6efQxRJZxrh785c3s61wd48Q6jXGGx9kx1fehzL/1yIrxbWlyfdAv+Y7VgXmNsb6sCuqBPtYhfe3qn5cPOiaLeljnfNit9W1cY5I7jS1jjtL1ky/vWj0m1hh1+vhcmzI91L/ax0k0xGHVtTljT3VE76Z60JZZIk/RtQ7I81pf8pBze76Qca3HfZcvrJ5M/VrzEm9heZfrmTs19QM5rxa6Jj7ldcmPu5/j7Yv11jLUk6tM+jE6lrG3Hk5DjC3lvF/jB4hPc5xjphjW+l6XWaseLeW8rz/DONXxeMyjZhjnmC6beg6UoaCrM1aM+k17nuqCMaQ3cXqX7xFnTV119EtdnA3DEifRHG/IEnNfTJLlhJjqUdVO8UqG+j6UBWgz5JwTs/gUb3PT5mlVP5cppuBygLXxrk553tfl7RhvS78MeRTUU2VtphgP60+4THHwljmpvqU5OTaxcinze8x8dWRd+npglfVxPYyWWOqUYbuPH6J/Z0rOw6sMivVsLCN/nfjjBCmHUZwQ8ec5aMfxWH64WNjMsZAu83Of33SKuaqJ5Wj90k2cOkPfxQp7jRVkPboK6kk5xFkxjPX4m2MWXOY6DpTxOj6XZYw1ZxcHX3ypcvC1OQd3cUbV42CKZWKuY4c4HOZuyYV3fTl5FVJO+ByWY6zrpnh34+1e4/WUySim4G6o70m5MIhxZe7ilcT7Xib4MaftGNOHWMPFarSLoyLWeGtfz5Uy9MXrqEdiWRg0sR5q64E1tPV7lIOlvltzLIDL2NLFMjFOkXiPhrjo6MrxHWPzVA+5Ia9P1maNkyQWIGUMjiu7cYmFbT1sly6n+Tp4lzVPXK/Ug7W8SbEIK8NiPc/WWIPFOneMBXB5n+vBuAz1S0+xRC5zfIyf5a2vA0qMdmWh18SUWb/H1NUZqsuZqixHYuSvR8o81nVLGazi6i4WjWUcj2uToY9rzJjaxzil53g/T0uM+sXncYgBc4wZLFf7S/2DoamjZFnV1hVOv8SRPedoVd/3KebzmCmGnJLb+HD7uY7/0xTfulxO1LFgyLmyjotDP8YYGyuC8sLq6LE29ZQvp/iUZ0QOanFM5iq0iTVwziFzfWumWFOcLvXiS9Ypbx3iTexjTD0tKOM6POaANcfnWCe1bUy1QyzCyuGTy+j4Qct0GQNFjF5LXLovfT1nh/gmU0wO63QeJ2L9FqvXPlbP5ZX3Md/EeiAO8yEP8zJyxtxdp5Wy3M65LGb38mbUlVaeEOXN6WNSr4dxmRrr8TI3U56IsViqp0o5WuJ6IEaW09kVOwrxEQ2x7hrj04+FcR+L7DIwxskWQ2fMit0as09cI3Xn9foUC4clLonKv+xjQVEPmDEuHsux3OSlUXyqXS6Y+/isyhTfxO5KDJJNTu1j7nnk0Fw+wyaWmVNejdb3dojRpyxz4xK/j+ku1zIxIZar7NgVmOvJPMa+Rrl0z4XEGmdvGdbjPa4c4iqxj3VBea/nPPHj06kDwmm3YonrlFg55wXMGsuCvslVYRsjaZvrxnJtGkNUW4e98km2MdvX2TBf/TD9eN2cFxX1+Fjicn2K5e8Qk0leEw/xYsemiwE1TqEy1MZ+WR2gyiATW2zxQ3UxHZXL37rpVRYn9Rp2/C9H9RTbdeUabskRNrah+rjKH6r0fSwWyzVrfNeYDfvYVCpLzvoZrHOel00cJWUUi6vrPv5xF1d6ZYKMnac2vm75SOe4Kou11hIT8Y/ryK5rckSIw72JfcG1i4VPnjkx+Zw2luKHiuO9b+oJXQbQJSaVJddA9VBaYwdgGkPO70kMnKfRusl3PC4s4kOe+7hQanJx3NYfqAz5+enHJUi8pj6uD09vxPD2dk6/1g8tN17KvBpXIjGwx1J0nOoht8QlwDTk8RWvJybNfjpfIcbcWf/e3E0x0s2xETXHjDHHPk4emVP8zGUBV4/QGD3Lwi6WJmNuBK5xak+xgdu0uS+c13Bz/OUyLMSSf4ktmqWeqUssMMukE6d2vKVdLAvm2JvIrcqy0o81X6ynY5+2rCfqwTCPU6wn4rgs1+zd22fvEFvTZSqNQ7ur720XY3wuK4Z4j8tEEjP4ee93yrNziMGrTJ5xwVRPyvK5LnnAx1XQlJuvzfDO+Vr+RexYLFPsfc1xVRo/4BRbrX0ctOMaY0RuQ4yxbptiTX06IcZ6tg6xbMwTMdeCU4zTUxufR0wCMamWtU8uy+Yurw3i857nuJAcu1iflEMj35e4il+62DIYY0yIZUj5mNo4QPNqJn/0uqAc5/zJ67ctlyr1QMnrpxx7c6DsY4wZY198iHdv7GPfY63v6hAbDOVyql6d5/7L1MUIUSfyMhKf59+YQ4bcYqo/0pwr7TLNLrnknmKXoL7aMW4exPcqZ23s4s6x09bFy+n7GKO7GLhiaVKuePPgjH3Ita69ysfR5kXpeSOwifm7jWuHIZYs8ZYvsX01xSbGGLtG/Zhj75zXDrHdP3W5GxNbA0tc3Jer0NgxjZsL5V1rc+e9j5ku9pfqVVJuS5fjJwaWOU6V8hLrXBjftCw34iCNLc22LA67uDiODesf9xLzWmzIDaj6PuW+bLn8aON6+7ydlPvH9SXGvn9ZM8Wyao7xvYws9ZAaptwqjHtWU58H3xRrs7iyyw++y62NZcj7DrGDWl5LbqXWCXSJkX9tz/dc4qp8zaOqi7VCLO+WuAsyxNK4i8vfsjyqjNsq59FgjS3qMa7qu9hELgdCnMG5ObrkPvwYf7LEdl3fnXcJ4xDpYwVVZtpYa+XFVjmI+tw9itte6/n2TswxQ86tMYm0cR+uLCTPh0lcyTRt/cvlw4ihYck95txQisOhzJ1xBzGusIYcG2Jfr7zK2Gysh/Uc+x3rOMQkUr/52OW23zLEvkcMCuuQq4T4zm2MxOfJsJ7xa2zSdHNcX5ZZNs7ONo+M2PTqm1iirLEHU2e+OS4zp9x2yO2qcljW75k77HlTLDdKT9eyccrVn3aNuwll8K+n0RrHYvl8Yk+piSmuyfVGm4NJXT+Ua9/4afOqps7sfZ8b8U09HMpRG/s7MdgMcVyXNfIQN/3G2CrLa5S4iOxj8y9HqdhrWmIKLYNp7mPk5tpUR5CyZGtj/zAWVbFPN631b64xHY2xK1jWI0uerzHrxGna5i5Em5Nb18UBOQ55PsaeQR9HzxgLjG7MWwx9bEmXl7DGTm8s0ef+7auksijNcye2zfvYfejHOvSscZdiiGX/GAvoeYibOX3cl2vLyNPEuqePLYFufntXqo87i+VqpomTIa7NmnpuD7lxPYx5TRv7nGNMtuUyuI2lUR2S1jZWzfMUy9RYCbTn7cvz9cpYB+JSxP5ZWQQ3MSPnBnmswNYceJfcaotxvix/4x5zXHFNbZd3v2KPcM2DPIvycmPbK6aIvospdIit1TLn5rHYTjnV59b88s58XD7J3FGKg7CMOfn4Qp14ylIwd2viM8wlzDDnDdr23ZtlY1s/ia6NxUk5DGI2jZvqZRUTx8FcP955zv2zGA6m3JNuu1z45jJ8jo2zMS7vprhRuq656JtzZyHvHo25I5WPDORhNsZNi3Y93zeKjaOuy0vWMe4O5bh/uvGxxA5MnF5rbOV3UzzXUE6VuMwa+7xNUM//Ne9Fj/Edh+G82Z5DZX371liHznlerfmRl6uIPBxzKyOuROYhL9HiuOnaGJjLOdzlwBr3OvKGzdTmSjAWP/HEwxCXFuXoiC3LLhYG5QyPgbKMufXtmuPwL1NfnHdTrNzmePbkdM7kraScwGJPohx0MVzmLZqhDLTxPePrnfaGY13XxtbYEkv3aTgvNnLpF015F/q3t3hOS9gc9mIKGGJ9Uk7G6Z3bMV2bC+FliNvVsTPYLVNsIrZ93sOMt6icnuv5LIhXO+Td09jpWvLLNGOXk0feMh9i0pvjjn1ZTta3aIjHTco6OT6uJabQMu3Xkyr2z05X47ECHXLrJB5AmfLaa4ntoT6nrz7XUksOfbHnNMTCZYo5dcqtr5ywT18rti7rn6x97mPknY92zfsU+ebPQ9xLzKv0Np+nyl3oPEPLh1EHpNwl62Ox0uazC+XDjq2afol5MO5UDHG/4bT3l/N7DKdx4sxx83Qe45K3vN15MzieSCmffj39yhePjyTWOPN5VRT3OU6PheWeVH1hZQ275DkcmzyxIbPmFlQ75g3eONDzi5weMIq/m7fby3Vn7FbE4zTDedjM++LT+QmTXD7lPd45F8GxH1/+oM4Tfa6bhm6Ou3hzDphxWJTRas3txNwTyoVzbk7G6uB0ebO8ey+5a3L+yaer8l5oOcNyNX++ZRU7yuXCL97LecyXFDdM+1hLdblkOj0ttLz90Ew579ucLfKJjXGMDfU2N8Pr+x5bL2UVldd8saA8LXLjiwxtPvNTZ98lBvwxF8R9fESne7fxZWO8Pd+ybnJajB3wObZd8sHAoY0zaon7Z+UnjPEhtjHKaJuXBEvOWzEATXFRd7qnMsQNqNhezK24mvP+35TjSb/mcyq5p1POnjmuJc8/eT65EtNbTJKnz3GNPcN4BCluoDVxS62cZ7nfGU/wrHkMzDEblxn3vJ0fK90lnu5oy/o7RsiY8ZZ4xKqcI3FsxYMK5YfMZwXGmO7LMJg3uOvRUaadPKXjLnRZh8Q9w9gA6E7HcUxfc9ysnPL5irV7+7PvznNJF7Nv+VDii6znczpupg25pRJj9hzblPGs1JDbs+P5fIizdIgzpVyRNOdxL64g8/uXC74cBnIZlwvWtcmX3OeAnrfIyvqiiduk+cbFPsCac2ITX6br4ghYm9x3iIGtfJVcmK65ND4vSpa4iGrGvFgaYnnb5MIp7uvNeaFy3vye41DPu0HlXM/5tM8HXnJPtHwgY96Oy/sOuYeew0o35j5fLhby3m151378aWI2jy2F/nTj8Z1Jrryhc+4gxuN35WK5j82uGOxjYXV6wjdXLDFaLnFjac7HHHN/rszquS8Qj2G2yxz306e4wXG6+oiHZc/jc9wAXuL8Kx98PsCyxnMrP77n8WTd0A35gNyYz5CcD4mY/MY4N8tnmY+7dHFDaYxl9bzmrBGf99q3ueSMJdAcj0+VUWrKtzFH+bw3s6znG1VDfssYQ9om17vDmiuJ2N3MCXGcc4iKR/bKsRYz7Zgr0yZuAZSVZJd/Z8j7/WNuHeTVcGyrl1fbx4/Tx/g4xlPWp0duciEQj1nPMZbmLdh8PGDI+5NlFoo3IJ61m3NLLR8vLvPVeYvhPNvHHu4UD9HMMc6UEzZvV+Ud6SkuVcvhHi9pbuNqvPzYOXDk47v56HIXB8np9uUQS+ohL93i6jmuX+a4kzfHdlxXhuQ4zc+bJvP5Xld8x2X8cYUUo08+JN3GirxcMkVTpsE4NvJ0Lsf3+do6twXi1Z0fXjzvdZQL1jjBYzNn6WMr73zh0K9r3kNvc381ni7v4mWWC8E5Z5oxPtw4gfJBpHIg5GO1uYdTfrwub6WseTM+7kOPeWcqngwp3zxXFXElXb55fB5zPFdQrlryUZ+4UI7nHLouJo7TRW1+vHEernnrcu5ytyKfgM1TtKxSxrjqiTF/ioud01NJOWvmDnKX28L51NdyfsI3F6Yx9J0XmWUyyNv+sU3fx4ZqOfmW2NeNg+M820/5CN+SzyKV5Xqc31MuNOJiYo6xsPzN80VqXChMQz5R9uPVaj76vr796HJ5c7t4hGzJp9C6euiWMS0+knjkraxYY3IY8qmyGDzyoabyw8ZThedfRFjy3krf56VDrnDaXPXnxVp5IXH7ZckLrtiPK4NKrHKX/KN+zV/SmPPJmXiy4/ycz7zGKbfGw26liUOx6/LYOd9yjsMrn2so3yGGti4eYClnUy5d4rn7cnLHk0xNXne1cWv+tLEVE0luNuT+XRnv85OMm3jt+bcJftyEGXO1Fw+u58Pl5Zhccs2Tt5risdNy0dnkhBeX/EMsxcdYz+TD7mWCiukonzVschl9ugKvI2vcM+ravLg7nwZ9XnTFTcZynq39O0+8d8Ocl2G5A13GoNz3j6uuNqes8bxfNsSdjzW2uMpZ38RfbmI0Kuvp3CWOhUgZNuMwn+N7ne8a5Zq/rBfiPI0Z5PSsWV4NxX2jIZ8HWPK2/xwPPZYFTtzRavP3VWIdPedlbhsPKZ3mrCGeWoqX2+QvFnVxfrZNPqKT2xJj7KGf9ldiOovjZ+hzfB7Ok2IOmnFhl3vdp6cop9zgyv2+ODvmvN04DDnMz3XaXfq8FuvygbLYQMtLvmXKy5TYXimru/gIxthFKfNVPN0SN99Ov9WUN6TjNea9mPZ8Y3OMQ3np84TIJ5SmeIZqGfIR8LhdE590+dDisZounos4zTtxoZHLtDnWCm2eyUOfWxzjebmba+O4ls8LiTVOxP78fMwaE3g7xNbK6QnY/N2IGCGb/sfnt4cY6ofcTe5z/ZMffjyTuS7nO5zLeTsrHymIX4KYzw91nZdgfV4XxgMnbf6CURmn8tPJZ0jnmETLmjF/cS2v3NpYc6xx32Fa65CRD92NXT7f17Rjju1xmuSTGWPsu592C2JlvMZlzvl+XJO/eRGXpmN+TPls74+3A5vzI9Xt+F8u1OZY9pcxNOfoKcfQvItTxtIxB8iYIPMpwLHJPcp8gKlcScXJvw7n30fq8jeF8ko110qxr3N6aDBO1zHXkfFrfeV7xiTf5JK9jav83Gg8PcgS521efaxrLlTjr5TVTizm13z+f851QBPnSJd37Kf8vPvzbw3EMxVlOIl7jG0+yBQ7Uqd1aRf3+2IXIZ/sjGfHp/9P17llSY4bS3BLQOC9/42JOGUWTPYcfV1daaa7KpME4uFuXqeShxTS6fxZ+opOamtLapNxJ9gbehzSYl+tugr6PK042Re9whUh2xKx+EM7ttQaVK08pdpYDVX/CAW